---
- name: Include install tasks
  include_tasks: install.yml
  tags: [install, openvpn]

- name: Include PKI/certificate tasks
  include_tasks: pki.yml
  tags: [pki, certificates, openvpn]

- name: Include server configuration tasks
  include_tasks: configure.yml
  tags: [configure, openvpn]

- name: Include firewall tasks
  include_tasks: firewall.yml
  tags: [firewall, openvpn]
